# Site settings
title: Junctionbox.ca
description: > # this means to ignore newlines until "baseurl:"
  Nathan Fisher's personal blog on all things software and development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://junctionbox.ca" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
github_username:  nfisher
#relative_permalinks: true

social:
  name: Nathan Fisher
  links:
    - https://github.com/nfisher

# Build settings
markdown: kramdown
sass:
  style: compressed
exclude: [bundle, vendor]

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1