# Site settings
title: Junctionbox.ca
description: > # this means to ignore newlines until "baseurl:"
  Nathan Fisher's personal blog on all things software and development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://junctionbox.ca" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
github_username:  nfisher
#relative_permalinks: true
social:
  name: Nathan Fisher
  links:
    - https://github.com/nfisher

# Build settings
markdown: kramdown
sass:
  style: :compressed
exclude: [bundle,vendor]

