source: source
destination: public
markdown: rdiscount
pygments: true
permalink: pretty

url: http://junctionbox.ca
title: JunctionBox.ca
author: Nathan Fisher
email: nfisher+jbx@junctionbox.ca #Add your email (optional) for the atom feed
simple_search: http://google.com/search

recent_posts: 10

twitter_user: junctionboxca
tweet_count: 3
show_replies: false

disqus_short_name: junctionboxca

google_analytics_tracking_id: UA-713228-10
